baseurl = "https://workers-safety.ca/"
# Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Workers Legal Clinic"
theme = "hugo-universal"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home / Page d'accueil"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name = "Legal Services"
    identifier = "menu.features.legal-services"
    url  = "/features/legal-services/"
    weight = 2

[[menu.main]]
    name = "Who we serve"
    identifier = "menu.who-we-serve"
    url  = "/menu/who-we-serve/"
    weight = 3

[[menu.main]]
    name = "Law reform"
    identifier = "menu.features.law-reform"
    url  = "/features/law-reform/"
    weight = 4

[[menu.main]]
    name = "Links"
    identifier = "menu.links"
    url  = "/menu/links/"
    weight = 5

[[menu.main]]
    name = "Communications"
    identifier = "menu.blog"
    url  = "/communications/"
    weight = 6

[[menu.main]]
    name = "Membership"
    identifier = "menu.member"
    url  = "/menu/member/"
    weight = 7

[[menu.main]]
    name = "About Us"
    identifier = "menu.about-us"
    url  = "/menu/about-us/"
    weight = 8

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/menu/contact/"
    weight     = 7


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:1-800-668-8258"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/TWHSLC/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://www.twitter.com/TWHSLC/"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:work@work.clcj.ca"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/communications/"
    author = "Workers"
    defaultKeywords = ["workers", "legal", "Ontario"]
    mainSections = ["communications"]
    defaultDescription = "Advocating for workers' rights"

    # Social media
    facebook_site = "TWHSLC" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "TWHSLC" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    # Instead of saving the api key in a config file it is saved in a Github secret and inserted in a Github Action.
    enableGoogleMaps = true
    googleMapsApiKey = "GOOGLE_MAPS_API_KEY"

    latitude = "43.6553678"
    longitude = "-79.3886179"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    # formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "6Ldr-vQZAAAAANkqk5sABD9TjKyNwwhYbCcS0c5I"

    about_us = <p><strong>Advocating for workers' rights / Défendre les droits des travailleurs<strong>
        <br>
        <br>Monday - Friday
        <br>9am - 5pm
        <br>
        <br>du lundi au vendredi
        <br>9 h à 17 h
        </p>
    copyright = "Copyright (c) 2023, WHSLC; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Workers' Health and Safety Legal Clinic"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/menu/contact"
    address = """<p class="text-uppercase"><strong>Workers' Health and Safety Legal Clinic</strong>
        <br>Monday - Friday
        <br>9am - 5pm
        <br>
        <br>180 Dundas St. West
        <br>Suite 2000, Box 4
        <br>Toronto, ON
        <br>M5G 1Z8
        <br>
        <strong>Canada</strong>
      </p>
      """

[permalinks]
    blog = "/communications/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us toll free 1-800-668-8258.</p>
      <p class="hidden-md hidden-lg"><a href="tel:1-800-668-8258" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:whslc@lao.on.ca" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Resources"
    subtitle = "We are here to help."

[params.recent_posts]
    enable = true
    title = "Communications"
    subtitle = "Here you will find our latest newsletters, public activities and more."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
