version: 2
jobs:
    build:
        working_directory: ~/workers-safety/workers-safety-website
        parallelism: 1
        shell: /bin/bash --login
        docker:
                - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
                  command: /sbin/init
        steps:
            - checkout
            - run:
                name: Deploying Site
                command: echo Deploying ${CIRCLE_BRANCH}
            - run:
                name: Installing dependencies.
                command: sudo pip install awscli
            - run:
                working_directory: ~/workers-safety/workers-safety-website
                command: 'echo ''America/New_York'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata; sudo service mysql restart; sudo service postgresql restart; '
            - run:
                working_directory: ~/workers-safety/workers-safety-website
                command: 'sudo docker info >/dev/null 2>&1 || sudo service docker start; '
            - deploy:
                name: Deploy to AWS S3
                command: |
                if [ "${CIRCLE_BRANCH}" = "stage"]; then
                  docker run -v $(pwd)/:/usr/src/blog clamorisse/hugo:0.15 hugo --baseUrl=http://stage.workers-safety.ca/   
                  docker run -d -p 1313:1313 --name hugostage -v $(pwd)/:/usr/src/blog clamorisse/hugo:0.15 hugo server --baseUrl=http://stage.workers-safety.ca/ --appendPort=false --bind=0.0.0.0
                  aws s3 rm s3://stage.workers-safety.ca/ --recursive
                  aws s3 sync public/ s3://stage.workers-safety.ca/
                  aws s3 sync newsletter-list/src/ s3://newsletter.workers-safety.ca/
                fi
